name: Generated APK AAB (Upload - Create Artifact To Github Action)

on:
  workflow_dispatch:
  push:
    branches: "*"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Fix gradle perms
        run: chmod +x ./gradlew
          
      - name: Build app
        run:  ./gradlew build
        
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/app/build/outputs/apk/
